### PR TITLE
New PR for Add Material Designer workflow example

### PR DESCRIPTION
**Pull request by vnamdeo**
Co-authored-by: JimmyHe0527 jimmy.he@ansys.com
Co-authored-by: vnamdeo vikas.namdeo@ansys.com"

### CODE REVIEW

**Comment by vnamdeo** [comment]
@Revathyvenugopal162 I have created a new PR for the PR#75, as this PR was forked. Could you please investigate and let me know the reason for failing. I checked the scripts and it's locally running fine.

**Comment by franknli** [comment]
> @Revathyvenugopal162 I have created a new PR for the PR#75, as this PR was forked. Could you please investigate and let me know the reason for failing. I checked the scripts and it's locally running fine.

@Revathyvenugopal162  The same error also show up in the main branch:

> Running vale...
>   /home/runner/vale --output=/home/runner/work/_actions/errata-ai/vale-action/reviewdog/lib/rdjsonl.tmpl --config=doc/.vale.ini doc
>   E100 [lintRST] Runtime error
>   
>   rst2html not found
>   
>   Execution stopped with code 1.
> Error: Vale and reviewdog exited with status code: 2

**Comment by Revathyvenugopal162** [comment]
> > @Revathyvenugopal162 I have created a new PR for the PR#75, as this PR was forked. Could you please investigate and let me know the reason for failing. I checked the scripts and it's locally running fine.
> 
> @Revathyvenugopal162 The same error also show up in the main branch:
> 
> > Running vale...
> > /home/runner/vale --output=/home/runner/work/_actions/errata-ai/vale-action/reviewdog/lib/rdjsonl.tmpl --config=doc/.vale.ini doc
> > E100 [lintRST] Runtime error
> > rst2html not found
> > Execution stopped with code 1.
> > Error: Vale and reviewdog exited with status code: 2

@vnamdeo @franknli  the issue is fixed in ansys actions and it will be working now

**Comment by vnamdeo** [comment]
Thanks @Revathyvenugopal162 for the quick fix. To merge the branch with the main, could you please approve it? This example has already been reviewed by Frank.

**Review by Revathyvenugopal162 — APPROVED** [review]

**Pull request merged**
